name: writefreely
version: 0.10.0-yuntan-git
license: AGPL-3.0
summary: A simple, federated blogging platform.
description: |
  WriteFreely is a beautifully pared-down blogging platform that's simple on the surface, yet powerful underneath.

  It's designed to be flexible and share your writing widely, so it's built around plain text and can publish to the fediverse via ActivityPub. It's easy to install and light enough to run on a Raspberry Pi.
type: app
grade: stable
confinement: strict
base: core18

parts:
  writefreely:
    build-environment:
    - GO111MODULE: "on"
    build-snaps:
    - go/1.12/stable
    - node/12/stable
    build-packages:
    - build-essential
    stage-packages:
    - sqlite3
    plugin: dump
    source: https://github.com/yuntan/writefreely.git
    source-commit: 0f851a2c6b271a8ef7f99d715fa63a4bfcea4f0a
    override-build: |
      go get github.com/jteeuwen/go-bindata/go-bindata
      # go get github.com/rakyll/statik
      export PATH=$PATH:$(go env GOPATH)/bin
      make ui build
      mv cmd/writefreely/writefreely $SNAPCRAFT_PART_INSTALL
    prime:
    - writefreely

apps:
  writefreely:
    command: writefreely
    plugs:
    - network
    - network-bind
